export enum Model{
    SP = "SIMPLE WITH PROFILE",
    SWP = "SIMPLE WITHOUT PROFILE",
    SD = "SIMPLE WITH DESCRIPTION",
    SWD = "SIMPLE WITHOUT DESCRIPTION",
    SDP = "SIMPLE WITH DESCRIPTION AND PROFILE",
    SWDP = "SIMPLE WITHOUT DESCRIPTION AND PROFILE"
    
}